[package]
name = "egg"
version = "0.8.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"
description = "An implementation of egraphs"
repository = "https://github.com/egraphs-good/egg"
readme = "README.md"
license = "MIT"
keywords = ["e-graphs"]
categories = ["data-structures"]

[dependencies]
symbolic_expressions = "5"
log = "0.4"
smallvec = { version = "1", features = ["union", "const_generics"] }
indexmap = "1"
instant = "0.1"
fxhash = "0.2"
hashbrown = "0.12"
thiserror = "1"
symbol_table = { version = "0.1", features = ["global"] }

# for the lp feature
coin_cbc = { version = "0.1.6", optional = true }

# for the serde-1 feature
serde = { version = "1", features = ["derive"], optional = true }
vectorize = { version = "0.2", optional = true }

# for the reports feature
serde_json = { version = "1", optional = true }

[dev-dependencies]
env_logger = { version = "0.9", default-features = false }
ordered-float = "2"

[features]
lp = ["coin_cbc"]
wasm-bindgen = ["instant/wasm-bindgen"]
serde-1 = [
    "serde",
    "indexmap/serde-1",
    "hashbrown/serde",
    "symbol_table/serde",
    "vectorize",
]
reports = ["serde-1", "serde_json"]

# private features for testing
test-explanations = []
